name: Edit and Commit 

on:
  workflow_dispatch: 

jobs:
  access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4

      - name: Go to target directory
        run: cd /.github/workflows/auto_push/ 

      - name: Open file and edit 
        run: echo "Adding text - this is a test" >> test_file.txt 
      
      - name: Add, commit, and push 
        run: | 
          git add text_file.txt 
          git commit "added minor text"
          git push origin master
        

