name: Edit and Commit 

on:
  push: 
    
jobs:
  access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4

      - name: Open file and edit 
        run: echo "Adding text - this is a test" >> .github/workflows/auto_push/test_file.txt 
      
      - name: Add, commit, and push 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/auto_push/test_file.txt 
          git commit -m "added minor text"
          git push origin HEAD:master